#Url de conexion a la base de datos
database.url=jdbc:mysql://127.0.0.1:3306/control_academico

#Credenciales de la base de datos
database.username=root

#Clave de la base de datos
database.password=12345

#Driver de la base de datos
database.driver=com.mysql.cj.jdbc.Driver